@startuml

title __JAVA's Class Diagram__\n

 namespace ro.mta.se.lab {
    class ro.mta.se.lab.Main {
        + void start(Stage primaryStage)
        <u>ReaderInterface reader
  }
 namespace ro.mta.se.lab {
      namespace controller {
        class ro.mta.se.lab.controller.ListController {
            + celsius : Label
            + chb_city : ComboBox<String>
            + chb_country : ComboBox<String>
            + description : Label
            + grade : Label
            + humidity : Label
            + precipitation : Label
            + showCity : Label
            + time : Label
            + weatherImage : ImageView
            + wind : Label
            - apiKey : String
            - currentCity : String
            - locations : Map<String, ArrayList<Location>>
            - weatherDescription : String
            + ListController()
            + getDescriptionInfo()
            + initialize()
            + showWeatherInfo()
            - handleSelectCity()
            - handleSelectCountry()
        }
      }
    }

    namespace ro.mta.se.lab {
      namespace model {
        class ro.mta.se.lab.model.Location {
            - ID : String
            - city : String
            - country : String
            - latitude : String
            - longitude : String
            + Location()
            + getCity()
            + getCountry()
            + getID()
            + getLatitude()
            + getLongitude()
        }
      }
    }



    namespace ro.mta.se.lab {
      namespace model {
        class ro.mta.se.lab.model.WeatherInfoClass {
            - cityName : String
            - description : String
            - humidity : String
            - precipitation : String
            - wind : String
            + WeatherInfoClass()
            + getCityName()
            + getDescription()
            + getHumidity()
            + getPrecipitation()
            + getWind()
        }
      }
    }

 namespace ro.mta.se.lab {
      class ro.mta.se.lab.Main {
          {static} + countryAndCity : Map<String, ArrayList<Location>>
          {static} + locations : ArrayList<Location>
          {static} - inFile : String
          {static} - scene : Scene
          + initializeCountries()
          {static} + main()
          + setRoot()
          + start()
          - loadFXML()
      }
    }

}

  ro.mta.se.lab.Main -up-|> javafx.application.Application
  ro.mta.se.lab.controller.ListController .up.|> javafx.fxml.Initializable

right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
